### PR TITLE
Initial cut

### PR DESCRIPTION
**Pull request by ehoogerbeets**
- scan source code for references to ilib packages
- collect locale data from those ilib packages
- write out js files with the merged data

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
Code works, but still needs documentation updates

**Comment by ehoogerbeets** [comment]
Ready for review

**Comment by gouniLee** [comment]
looks like there is a sample ilib-mock package, In order to see the final output js files, what should I do?

**Comment by ehoogerbeets** [comment]
You can try `node src/index.mjs output test` using node 16 or higher and then look at the files in the output directory

**Comment by gouniLee** [comment]
> You can try `node src/index.mjs output test` using node 16 or higher and then look at the files in the output directory

I checked js files are generated. In ilib-mock packages, there are only de-DE, en-US, and root locale data. but the js files are many due to the default locale setting. and many of them are duplicated. is it your intention?

**Comment by ehoogerbeets** [comment]
Yes, because if a locale has no settings of its own, then it uses the root settings. So, if the set of locales you are asking it to generate includes locales that have no settings, they are all copies of the root.

**Review by gouniLee — APPROVED** [review]

**Pull request merged**
